version: "3"

services:
    WebGPU:
        container_name: "WebGPU"
        image: nginx:1.14.2-alpine
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./dist:/usr/share/nginx/html:ro